// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"pehlione.com/app/pkg/view"
	"pehlione.com/app/templates/layout"
)

func Cart(flash *view.Flash) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layout.Base("Shopping Cart", flash, CartBody()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func CartBody() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-4xl mx-auto px-4 py-8\"><h1 class=\"text-3xl font-bold mb-8\">Shopping Cart</h1><div class=\"grid grid-cols-1 lg:grid-cols-3 gap-8\"><!-- Cart Items --><div class=\"lg:col-span-2\"><div class=\"border rounded-lg p-6\"><p class=\"text-gray-600 text-center py-12\">Your cart is empty. <a href=\"/products\" class=\"text-indigo-600 hover:text-indigo-700 font-semibold\">Continue shopping</a></p></div></div><!-- Cart Summary --><div class=\"lg:col-span-1\"><div class=\"border rounded-lg p-6 sticky top-6\"><h2 class=\"text-xl font-semibold mb-4\">Order Summary</h2><div class=\"space-y-3 mb-6 pb-6 border-b\"><div class=\"flex justify-between text-gray-700\"><span>Subtotal</span> <span>$0.00</span></div><div class=\"flex justify-between text-gray-700\"><span>Shipping</span> <span>$0.00</span></div><div class=\"flex justify-between text-gray-700\"><span>Tax</span> <span>$0.00</span></div></div><div class=\"flex justify-between text-lg font-semibold mb-6\"><span>Total</span> <span>$0.00</span></div><button disabled class=\"w-full px-4 py-3 bg-indigo-600 text-white rounded hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition font-semibold\">Proceed to Checkout</button> <a href=\"/products\" class=\"block text-center mt-4 text-indigo-600 hover:text-indigo-700 font-semibold\">Continue Shopping</a></div></div></div><div class=\"mt-12 p-6 bg-blue-50 border border-blue-200 rounded-lg\"><h3 class=\"font-semibold text-blue-900 mb-2\">💡 How to use the cart:</h3><ul class=\"text-blue-900 text-sm space-y-1\"><li>• Visit the <a href=\"/products\" class=\"underline font-semibold\">Products page</a> to add items</li><li>• Click \"Add to Cart\" buttons to add products</li><li>• Cart badge in header updates in real-time via HTMX</li><li>• Return here to review items before checkout</li></ul></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
