// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"pehlione.com/app/pkg/view"
	"pehlione.com/app/templates/layout"
)

func Company(flash *view.Flash) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layout.Base("Company", flash, CompanyBody()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func CompanyBody() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-4xl mx-auto px-4 py-12\"><h1 class=\"text-4xl font-bold mb-6\">About Pehlione</h1><div class=\"prose max-w-none space-y-6\"><section><h2 class=\"text-2xl font-semibold mb-3\">Our Mission</h2><p class=\"text-gray-700\">At Pehlione, we're committed to building innovative e-commerce solutions that empower businesses and delight customers.</p></section><section><h2 class=\"text-2xl font-semibold mb-3\">What We Do</h2><p class=\"text-gray-700\">We provide a modern platform for online commerce, featuring:</p><ul class=\"list-disc list-inside text-gray-700 space-y-2 ml-2\"><li>Real-time inventory management</li><li>Secure payment processing</li><li>Advanced cart and checkout experience</li><li>Order tracking and management</li><li>Admin dashboard with analytics</li></ul></section><section><h2 class=\"text-2xl font-semibold mb-3\">Technology Stack</h2><p class=\"text-gray-700\">Built with modern technologies for performance and reliability:</p><ul class=\"list-disc list-inside text-gray-700 space-y-2 ml-2\"><li>Go + Gin Web Framework</li><li>Templ for Server-Side Rendering</li><li>MySQL InnoDB Database</li><li>Tailwind CSS v4 for Styling</li><li>HTMX for Dynamic Interactions</li></ul></section><section><h2 class=\"text-2xl font-semibold mb-3\">Contact</h2><p class=\"text-gray-700\">Have questions? Reach out to us at:</p><ul class=\"text-gray-700 space-y-1 ml-2\"><li><strong>Email:</strong> hello@pehlione.com</li><li><strong>Website:</strong> www.pehlione.com</li></ul></section></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
