version: "2"

run:
  timeout: 3m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - errcheck